# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "CnZngn"
  url = "#content/CnZngn/admin/_index.md"
  weight = 10

[[main]]
  name = "Research"
  url = "#content/Research/Research.md"
  weight = 20

[[main]]
  name = "Teaching"
  url = "#content/Teaching/experience.md"
  weight = 30

[[main]]
  name = "CV"
  url = "#content/CV/CV.pdf"
  weight = 40

[[main]]
  name = "Contact" 
  url = "#content/Contact/contact.md"
  weight = 50




